# Generated by Django 5.2.7 on 2025-11-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can create books'), ('can_delete', 'Can delete books')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_create', 'Can create items'), ('can_delete', 'Can delete items')]},
        ),
    ]
