# Generated by Django 5.2.8 on 2025-11-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the author', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=200)),
                ('publication_year', models.IntegerField(help_text='Year the book was published')),
                ('author', models.ForeignKey(help_text='Author who wrote this book', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='api.author')),
            ],
            options={
                'ordering': ['-publication_year', 'title'],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
